version: "3.7"
services:
  php-fpm:
    container_name: pathfinder-php-fpm
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - web
  nginx:
    container_name: pathfinder-nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    networks:
      - web
    labels:
      - "traefik.http.routers.pathfinder.rule=Host(`example.com`)"
      - "traefik.http.routers.pathfinder.entrypoints=websecure"
      - "traefik.http.routers.pathfinder.tls.certresolver=secure"
      - "traefik.docker.network=web"
      - "traefik.port=80"
      - "traefik.enable=true"
  mysql:
    container_name: pathfinder-mysql
    restart: unless-stopped
    image: mysql:5.7
    volumes:
      - ./.docker/mysql/aa_init.sql:/docker-entrypoint-initdb.d/aa_init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - web
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
  redis:
    container_name: pathfinder-redis
    restart: unless-stopped
    image: redis:5.0.5-alpine
    volumes:
      - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    networks:
      - web
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--appendonly yes"]
  websocket:
    container_name: pathfinder-websocket
    restart: unless-stopped
    build:
      context: ./.docker/websocket
      dockerfile: Dockerfile
    networks:
      - web
  # Development Only
  # adminer:
  #   image: adminer
  #   ports:
  #     - 8081:8080
  #   networks:
  #     - web

volumes:
  mysql_data:
  redis_data:

networks:
  web:
    external: true
